version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgresql-container
    restart: always
    environment:
      POSTGRES_DB: swift_code_parser_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: no
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5432/swift_code_parser_db
      DB_USER: admin
      DB_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgres_data:
