version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgresql-container
    restart: always
    environment:
      POSTGRES_DB: swift_code_parser_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
